language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5

os:
    - linux

install:
    - pip install tox
    - pip install coveralls

script: 
    - tox
    - python setup.py test --addopts "-v --cov pathvalidate --cov-report term-missing"

after_success:
    - coveralls
